Update plugins.json
ReviveUnblockNCMInstaller/RevivedUnblockInstaller pull request #19
Opened 2023-08-23 08:30 UTC by GADDQ

[RevivedNcmDump.zip](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/files/12417031/RevivedNcmDump.zip)
这样就可以了吗？

2023-08-23 16:30 UTC, ReviveUnblockNCMInstaller requested changes
把你的插件打包好，命名为 RevivedNcmDump.plugin，一同放在这个 pr 里发上来

2023-09-09 12:52 UTC, GADDQ commented
前阵因个人问题没有上线，现在回来解释一下
这个zip就是plugin，由于github的pr不可以上传.plugin文件，我压缩了一下
还请麻烦手动操作一下！

2023-09-10 01:20 UTC, ReviveUnblockNCMInstaller commented
可以上传 .plugin 啊，你想上传什么都可以，唯一的限制是文件大小不能超过 25M

2023-09-17 07:48 UTC, GADDQ commented
pr的上传无法上传.plugin，所以传上来的是zip
另外为我的一周回一次消息抱歉 本人住校 一周只放一天

2023-09-17 07:54 UTC, GADDQ commented
![Screenshot_20230917-155355_Chrome](https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/assets/60539984/92d3d83f-8534-4bb5-96bf-9d7a8b2947bd)
此为证明

2023-09-17 13:30 UTC, MicroCBer commented
> pr的上传无法上传.plugin，所以传上来的是zip
> 另外为我的一周回一次消息抱歉 本人住校 一周只放一天

是让你传到repo里吧...

2023-10-04 02:32 UTC, ReviveUnblockNCMInstaller commented
是的

2023-12-22 15:11 UTC, ReviveUnblockNCMInstaller commented
还在做吗，不做我关了噢

2024-01-28 08:55 UTC, closed without merging